version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordppress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usuariopadrao
      WORDPRESS_DB_PASSWORD: senhapadrao
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wordpress:/var/www/html
      - ./src/tema:/var/www/html/wp-content/themes/meu-plugin
      - ./src/plugin:/var/www/html/wp-content/plugins/meu-plugin
     

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    depends_on: 
      - mysql
    image: adminer
    container_name: adminer
    restart: always
    ports: 
      - 8888:8080

networks: 
  back:
